add config load for r

diff --git a/setup/bash/bash_functions b/setup/bash/bash_functions
--- a/setup/bash/bash_functions
+++ b/setup/bash/bash_functions
@@ -7,6 +7,15 @@ r() {
       DOTFILES_REPO_DIR=$(pwd)
     else
       IS_PROJECT_ROOT=false
+
+      # --- Load Configuration ---
+      DOTFILES_CONFIG_FILE="$HOME/.bash_extras/.dotfile_config"
+      if [ -f "$DOTFILES_CONFIG_FILE" ]; then
+          source "$DOTFILES_CONFIG_FILE"
+      else
+          t Error "Configuration file not found at $DOTFILES_CONFIG_FILE" >&2
+          exit 1
+      fi
     fi
 
     echo "[INFO] Resetting settings.."
@@ -20,7 +29,7 @@ r() {
     fi
 
     ./install.sh
-  
+
     if [ "$IS_PROJECT_ROOT" = false ]; then
       popd > /dev/null
     fi
