refactor config stuff

diff --git a/setup/bash/bash_functions b/setup/bash/bash_functions
--- a/setup/bash/bash_functions
+++ b/setup/bash/bash_functions
@@ -3,19 +3,23 @@
 # Re-run Dotfile installation
 r() {
     if [[ "$(pwd)" == *"/dotfiles" ]]; then
-      IS_PROJECT_ROOT=true
-      DOTFILES_REPO_DIR=$(pwd)
+        IS_PROJECT_ROOT=true
+        DOTFILES_REPO_DIR=$(pwd)
     else
-      IS_PROJECT_ROOT=false
+        IS_PROJECT_ROOT=false
 
-      # --- Load Configuration ---
-      DOTFILES_CONFIG_FILE="$HOME/.bash_extras/.dotfile_config"
-      if [ -f "$DOTFILES_CONFIG_FILE" ]; then
-          source "$DOTFILES_CONFIG_FILE"
-      else
-          t Error "Configuration file not found at $DOTFILES_CONFIG_FILE" >&2
-          exit 1
-      fi
+        # --- Start Load Configuration ---
+        if [ -z "$DOTFILES_CONFIG_FILE" ]; then
+            DOTFILES_CONFIG_FILE="$HOME/.config/dotfiles/.dotfile_config.env"
+        fi
+
+        if [ -f "$DOTFILES_CONFIG_FILE" ]; then
+            source "$DOTFILES_CONFIG_FILE"
+        else
+            t Error "Configuration file not found at $DOTFILES_CONFIG_FILE" >&2
+            exit 1
+        fi
+        # --- End Load Configuration ---
     fi
 
     echo "[INFO] Resetting settings.."
