fix config dir in install

diff --git a/setup/bash/bash_functions b/setup/bash/bash_functions
--- a/setup/bash/bash_functions
+++ b/setup/bash/bash_functions
@@ -16,7 +16,7 @@ r() {
         if [ -f "$DOTFILES_CONFIG_FILE" ]; then
             source "$DOTFILES_CONFIG_FILE"
         else
-            t Error "Configuration file not found at $DOTFILES_CONFIG_FILE" >&2
+            echo "[Error] Configuration file not found at $DOTFILES_CONFIG_FILE" >&2
             exit 1
         fi
         # --- End Load Configuration ---
