update personal and twork bash

diff --git a/setup/bash/bash_functions b/setup/bash/bash_functions
--- a/setup/bash/bash_functions
+++ b/setup/bash/bash_functions
@@ -363,20 +363,20 @@ rrr() {
 # Copy generic .bash_twork starter file
 set-tworktt() {
     if [ -z "$DOTFILES_REPO_DIR" ]; then
-        t ERROR "DOTFILES_REPO_DIR not set, check $HOME/.config/dotfiles/.dotfile_config"
+        t ERROR "DOTFILES_REPO_DIR not set, check ${FILE_F}$HOME/.config/dotfiles/.dotfile_config${NC}"
         exit 1
     else
         if [ -z "$DOTFILES_CONFIG_DIR" ]; then
             DOTFILES_CONFIG_DIR="$HOME/.config/dotfiles"
         fi
 
-        t "Generating basic tworktt file"
+        t "Generating basic tworktt file.."
         TWORKTT_FILE="$DOTFILES_REPO_DIR/setup/_templates/twork-template.txt"
         if [ -f "$TWORKTT_FILE" ]; then
             cpp -q "$TWORKTT_FILE" "$DOTFILES_CONFIG_DIR/.bash_twork"
-            t SUCCESS "All set! Remember to edit .bash_twork"
+            t SUCCESS "All set! Remember to edit ${FILE_F}.bash_twork${NC} at ${DIR_F}~/.config/dotfile${NC}"
         else
-            t Error "twork-template.txt file not found at $DOTFILES_REPO_DIR/setup/_templates" >&2
+            t Error "${FILE_F}twork-template.txt${NC} file not found at ${DIR_F}$DOTFILES_REPO_DIR/setup/_templates${NC}" >&2
             exit 1
         fi
     fi
@@ -385,20 +385,20 @@ set-tworktt() {
 # copy generic .bash_personal starter file
 set-ptt() {
     if [ -z "$DOTFILES_REPO_DIR" ]; then
-        t ERROR "DOTFILES_REPO_DIR not set, check $HOME/.config/dotfiles/.dotfile_config"
+        t ERROR "DOTFILES_REPO_DIR not set, check ${FILE_F}$HOME/.config/dotfiles/.dotfile_config${NC}"
         exit 1
     else
         if [ -z "$DOTFILES_CONFIG_DIR" ]; then
             DOTFILES_CONFIG_DIR="$HOME/.config/dotfiles"
         fi
 
-        t "Generating basic personal file"
+        t "Generating basic personal file.."
         TWORKTT_FILE="$DOTFILES_REPO_DIR/setup/_templates/personal-template.txt"
         if [ -f "$TWORKTT_FILE" ]; then
             cpp -q "$TWORKTT_FILE" "$DOTFILES_CONFIG_DIR/.bash_personal"
-            t SUCCESS "All set! Remember to edit .bash_personal"
+            t SUCCESS "All set! Remember to edit ${FILE_F}.bash_personal${NC} at ${DIR_F}~/.config/dotfile${NC}"
         else
-            t Error "personal-template.txt file not found at $DOTFILES_REPO_DIR/setup/_templates" >&2
+            t Error "${FILE_F}personal-template.txt${NC} file not found at ${DIR_F}$DOTFILES_REPO_DIR/setup/_templates${NC}" >&2
             exit 1
         fi
     fi
