fix bash init

diff --git a/setup/bash/init b/setup/bash/init
--- a/setup/bash/init
+++ b/setup/bash/init
@@ -1,8 +1,20 @@
+# --- Start Load Configuration ---
+if [ -z "$DOTFILES_CONFIG_FILE" ]; then
+    DOTFILES_CONFIG_FILE="$HOME/.config/dotfiles/.dotfile_config.env"
+fi
 
-if [[ -f "$HOME/.bash_extras/.bash_colours" ]]; then
-    . "$HOME/.bash_extras/.bash_colours"
-elif [[ -f "$DOTFILES_REPO_DIR/bash/bash_colours" ]]; then
-    . "$DOTFILES_REPO_DIR/bash/bash_colours"
+if [ -f "$DOTFILES_CONFIG_FILE" ]; then
+    source "$DOTFILES_CONFIG_FILE"
+else
+    echo "[Error] Configuration file not found at $DOTFILES_CONFIG_FILE" >&2
+    exit 1
+fi
+# --- End Load Configuration ---
+
+if [[ -f "$DOTFILES_CONFIG_DIR/.bash_colours" ]]; then
+    . "$DOTFILES_CONFIG_DIR/.bash_colours"
+elif [[ -f "$DOTFILES_REPO_DIR/setup/bash/bash_colours" ]]; then
+    . "$DOTFILES_REPO_DIR/setup/bash/bash_colours"
 else
     echo "[WARNING] Failed to load colours"
 fi
